### ISSUE TITLE
How do I trigger a Media Player input

### ISSUE THREAD

**Issue by marty6001** [npope/home-assistant-crestron-component#17]
I'll start this by saying that I am very new at HA - I am however a Crestron veteran. 

I was able to configure HA with the instructions provided, and my Crestron system is connecting successfully to HA.

Now for the part that should be very easy: How do I create a card on a dashboard that changes the volume, input, mute, etc...? I get this message whenever I try and do just about anything with the object:
![KitchenSpeakers](https://github.com/npope/home-assistant-crestron-component/assets/154853658/7a043e4f-6f4e-4744-ac3d-efc3dd6bb618)

Thanks in advance.

**Comment by sebastiensoulac** [comment]
Hello,
I have the sam problem
did you find the solution because I have the same problem?
Thank you for your feedback.

**Comment by marty6001** [comment]
No, I haven't been able to make it work yet (to be honest, I haven't had that much to dedicate to it)

**Comment by sebastiensoulac** [comment]
@marty6001 
thank you for your feedback.
Unfortunately no one is replying to me on the various forums.

**Comment by sebastiensoulac** [comment]
Logger: homeassistant.setup
Source: setup.py:393


First occurred: 17:19:08 (2 occurrences)
Last logged: 17:19:08

Unable to prepare setup for platform crestron.media_player: Unable to set up component.
Unable to prepare setup for platform crestron.binary_sensor: Unable to set up component.

**Comment by sebastiensoulac** [comment]
Cette erreur provient d'une intégration personnalisée

Logger: homeassistant.setup
Source: custom_components/crestron/crestron.py:21
Integration: Crestron XSIG Integraton (documentation)
First occurred: 17:19:08 (1 occurrences)
Last logged: 17:19:08

Error during setup of component crestron
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 283, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/crestron/__init__.py", line 79, in async_setup
    await hub.start()
  File "/config/custom_components/crestron/__init__.py", line 128, in start
    await self.hub.listen(self.port)
  File "/config/custom_components/crestron/crestron.py", line 21, in listen
    server = await asyncio.start_server(self.handle_connection, "0.0.0.0", port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 85, in start_server
    return await loop.create_server(factory, host, port, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1525, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 8123): address in use

**Comment by sebastiensoulac** [comment]
here are the two mistakes.
On my toolbox my TCP/IP is properly connected
