### ISSUE TITLE
Issue with Stop Cover

### ISSUE THREAD

**Issue by adamjs83** [npope/home-assistant-crestron-component#2]
When pressing Stop Cover we get this error

2021-04-12 14:56:16 DEBUG (MainThread) [custom_components.crestron.crestron] Sending Digital: 3, 1
2021-04-12 14:56:16 DEBUG (MainThread) [custom_components.crestron.crestron] Sending Digital: 3, 0
2021-04-12 14:56:16 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140109363592592] Cannot be called from within the event loop
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/config/custom_components/crestron/cover.py", line 125, in async_stop_cover
    call_later(self.hass, 0.2, self._hub.set_digital(self._stop_join, 0))
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 123, in factory
    async_remove = run_callback_threadsafe(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 50, in run_callback_threadsafe
    raise RuntimeError("Cannot be called from within the event loop")
RuntimeError: Cannot be called from within the event loop

**Comment by arimorcos** [comment]
@npope Any idea why this is happening? I'm also having this issue. Thank you so much for writing this library!
